Network Client
SandroBoka/iOS-WeatherApp pull request #7
Opened 2024-10-23 08:35 UTC by SandroBoka

WeatherService doesn't create an endpoint and make the call itself anymore, now that functionality has been delegated to NetworkClient which adheres to BaseApiClientProtocol and the endpoint is created using WeatherEndpointFactory which returns WeatherEndpoint which adheres to Endpoint protocol.

2024-10-29 11:00 UTC, dnikolic98 requested changes

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/.gitignore
> +Pods/
I believe you can remove this file since you already added one to the root

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityScreen/WeatherResponse.swift
> +    let deg: Int
`degrees`

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityScreen/WeatherResponse.swift
> +    let tempMax: Double
`minimalTemperature`
`maximalTemperature`

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityScreen/WeatherResponse.swift
> +    let temp: Double
`temperature`

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityScreen/WeatherResponse.swift
> +        case sys
`system`

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Clients/Endpoint.swift
> +        }
could be single line

`guard let url = urlComponents?.url else { return nil }`

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityListScreen/CityModel.swift
>      let id = UUID()
Not needed for this PR. However, down the line we will update the id to something else.

Problem with UUID is that its not a stable identifier since it will be changed with an every instance of the City model

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +        weatherService.fetchWeather(for: city.name) { [ weak self ] result in
no space in weak self -> `[weak self]`

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +                    DispatchQueue.main.async { [ weak self ] in
no space in weak self -> `[weak self]`

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +            guard let self = self else { return }
you can only write `guard let self else { return }` if what you are nil checking will be named the same as the current value

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityScreen/CityScreenViewModel.swift
> +                DispatchQueue.main.async { [ weak self ] in
`[weak self]`

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +        City(name: "Split")]
`private(set) this variable` -> `@Published private(set) var cities: [City]`

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +                        self?.cities[index].temperature = weatherResponse.main.temp
I would like to make `cities[index]` safer. Create an extension on an array with a generic `func at(_ index: Int) -> T?`

I would like you to find a way to implement this function in a way that is safe from `index out of bounds` exception

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +                    DispatchQueue.main.async { [ weak self ] in
Also why did you make this safe?

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Clients/NetworkClient.swift
> +                guard (200...299).contains(httpResponse.statusCode) else {
this could have been under the same guard statement. Currentyl nothing happens if the response is optional

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Clients/NetworkClient.swift
> +public protocol BaseApiClientProtocol {
no need for public

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Clients/NetworkClient.swift
> +public enum ClientError: Error {
no need for public

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Clients/Endpoint.swift
> +public protocol Endpoint {
no need for public

2024-10-29 11:00 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Services/WeatherService.swift
> +        guard let apiKey = Bundle.main.infoDictionary?["API_KEY"] as? String else { fatalError("API Key not found") }
We could also extract `"API_KEY"` into some kind of constants. Maybe create an enum called InfoConstants with static let strings for keys

2024-10-29 12:15 UTC, SandroBoka commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +                    DispatchQueue.main.async { [ weak self ] in
To be extra safe

2024-10-30 08:08 UTC, SandroBoka commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +                        self?.cities[index].temperature = weatherResponse.main.temp
I did it, but you should check it out still.

2024-10-30 10:46 UTC, dnikolic98 requested changes

2024-10-30 10:46 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +    }
Extract this into a new file -> Array+Extensions.swift (on the other PR this should be moved under Core->Extensions)

Make sure to add new lines before and after as well

Also remove return as it is not needed in this case

2024-10-30 10:46 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +                if let index = self.cities.firstIndex(where: { $0.id == city.id }),
Would be neater to use guard let here

2024-10-30 10:46 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +                   self.cities.at(index) != nil {
also here you are only checking if its not nil and in the DispatchQueue you are using subscript to extract the city for index.

Proper approach would be to `let` this value and use it moving forward

2024-10-30 10:46 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityScreen/CityScreenViewModel.swift
> +    @Published var weather: CurrentWeatherResponse?
private(set) both `@Published `properties

Make sure to check other view models as well and fix acorrdingly

2024-10-30 10:46 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Clients/NetworkClient.swift
> +            guard let httpResponse = response as? HTTPURLResponse, (200...299).contains(httpResponse.statusCode) else {
On multi-statement guards, every guard statement should go to its own line

```swift
guard 
    let httpResponse = response as? HTTPURLResponse, 
    (200...299).contains(httpResponse.statusCode) 
else {
```

2024-10-30 10:46 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Clients/NetworkClient.swift
> +                completion(.failure(.httpError((response as? HTTPURLResponse)?.statusCode ?? -1)))
`(response as? HTTPURLResponse)?.statusCode ?? -1` extract this and use as a variable to make it easier to read

2024-10-30 10:46 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Services/WeatherService.swift
> +
extract to its own file

2024-10-30 10:46 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Services/WeatherService.swift
> +    static let apiKey = "API_KEY"
on the other thought you can make this static computed property to retrieve the info.plist constant directly and return it as optional

Just make sure to be more descriptive:  `apiKey` -> `openWeatherMapApiKey`

2024-10-30 10:46 UTC, dnikolic98 commented on WeatherApp/WeatherApp/CityListScreen/CityListViewModel.swift
> +                        self?.cities[index].temperature = weatherResponse.main.temp
Left a note 😄

2024-10-31 09:58 UTC, dnikolic98 requested changes

2024-10-31 09:58 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Services/WeatherService.swift
> +        }
could be in the same line if it fits
`       guard let apiKey = InfoConstants.openWeatherMapApiKey else { fatalError("API Key not found") }
`       
       else:
       
```swift
       guard let apiKey = InfoConstants.openWeatherMapApiKey else { 
           fatalError("API Key not found")
        }
```

2024-10-31 09:58 UTC, dnikolic98 commented on WeatherApp/WeatherApp/Clients/NetworkClient.swift
> +        }
also check the other guards with the single statement

2024-10-31 09:59 UTC, dnikolic98 commented
Also you will need to merge the develop into this to resolve conflicts

2024-10-31 12:44 UTC, merged